server:
  port: 80

spring:
  datasource: #数据库配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${datasource.url}?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true&failOverReadonly=false&maxReconnects=10
    username: root
    password: 19980925
    hikari:
      maximum-pool-size: 10 #最大连接池数
      max-lifetime: 1770000

  resources:
    static-locations:
      - classpath:/templates/
      - classpath:/static/

#数据库地址
datasource:
  url: localhost:3306/computer-network


mybatis:
  #指定别名设置的包为所有entity
  type-aliases-package: com.nju.entity
  configuration:
    map-underscore-to-camel-case: true #驼峰命名规范

  mapper-locations: # mapper映射文件位置
    - classpath:com/nju/mapper/*.xml


#交换机的配置
#switch:
#  ip: 172.16.0.1
#  port: 23
#  user: user
#  password: 123456
#  enablePassword: 123456

#交换机的配置
switch:
  ip: 172.19.240.90
  port: 23
  user: root
  password: 19980925
  enablePassword: 123456

#路由器的配置
router:
  ip: 172.16.0.1,172.16.0.2,172.16.0.3
  port: 23
  user: user
  password: 123456
  enablePassword: 123456

#路由器端口的配置命令
routerInterface:
  router1:
    conf t,
    int s0/0/0,
    ip add 172.17.0.1 255.255.255.0,
    no shutdown,
    exit
  router2:
    conf t,
    int s0/0/1,
    ip add 172.18.0.1 255.255.255.0,
    no shutdown,
    int s0/0/0,
    ip add 172.17.0.2 255.255.255.0,
    no shutdown,
    exit
  router3:
    conf t,
    int s0/0/0,
    ip add 172.18.0.2 255.255.255.0,
    no shutdown,
    exit

#静态路由的配置命令
staticRouter:
  router1:
    conf t,
    ip route 172.18.0.0 255.255.255.0 s0/0/0
#  router2:
#    conf t,
#    ip route 172.16.0.0 255.255.0.0 172.16.0.1
  router3:
    conf t,
    ip route 172.17.0.0 255.255.255.0 s0/0/0


#ping的配置命令
ping:
  router1:
    ping 172.18.0.2
  #  router2:
  #    conf t,
  #    ip route 172.16.0.0 255.255.0.0 172.16.0.1
  router3:
    ping 172.17.0.1